### ISSUE TITLE
Being prompted to buy a license even though a license has already been purchased and  added.

### ISSUE THREAD

**Issue by perrupa** [SublimeGit/SublimeGit#128]
I am currently being prompted to buy a license for SublimeGit every now and then even though a license has already been purchased and added.

I've tried removing and adding the license again and the problem persists.

**Comment by michaelpedersen** [comment]
Every instance of this i've experienced so far has been license not being entered properly. Gonna assume the same here. Please reopen if i'm mistaken.

**Comment by alexmilesyounger** [comment]
I'm experiencing the same problem: being prompted to buy a license even though I've added my license. I'm not sure how I could be entering it incorrectly because the process is very straightforward. 

Here's what I'm doing, please let me know what I should change in my process. 

* SublimeGit: Add License
* You already have a license installed. Do you want to overwrite it?
** Email: REDACTED
** License key: REDACTED
* Overwrite
* Prompt to enter email: MYEMAIL
* Prompt to enter License Key: MYLICENSE
* Thank you. Your license has been installed. Please restart Sublime Text.
* Restart Sublime Text. 

Thanks for your help.

**Comment by michaelpedersen** [comment]
Hi Alex, please get in touch on support at sublimegit dot net with the actual email and license. That will make it much easier to debug.

**Comment by alexmilesyounger** [comment]
Hi Michael, thanks, but I realized it was just dumb user error on my part. I was using my Order ID instead of my License. Thanks for offering to help, and sorry to bug you. SublimeGit is awesome and I'm so glad to have it in my toolkit.
