### ISSUE TITLE
Partial commit

### ISSUE THREAD

**Issue by julio6114** [SublimeGit/SublimeGit#183]
Hi!

I would like to know if it's possible to integrate possibility to commit a piece of code instead of file?

Thanks

**Comment by mhenrixon** [comment]
Sometimes it is but it is working terribly bad. For the file below I can't select just the bottom lines for commit. I have to select the entire file which sucks because I have to open tower to pick specific stuff to commit (or use the command line).

![default rb proxy-server 2015-03-01 12-13-01](https://cloud.githubusercontent.com/assets/106795/6430499/848859e6-c00c-11e4-80a8-eb0561fd700a.png)

**Comment by miped** [comment]
Same as #11 and #12. Closing.
