### ISSUE TITLE
Project abandoned? Please move it.

### ISSUE THREAD

**Issue by buildersbrewery** [SublimeGit/SublimeGit#225]
Hello @miped,

what is the current status of this project? It seems you have open sourced it and not much has changed ever since. Would you consider moving the repo to [github.com/SublimeText](https://github.com/SublimeText) for others to continue working on it?

**Comment by sbuttgereit** [comment]
It's very quiet here.  Too quiet.  I get that projects like these take time, but I hate it when they just go dark without transitioning stewardship of the project to someone with the time and inclination to manage it; I'm speaking as someone that purchased this before it was open sourced.

Having said that, this is one of the better Git tools for SublimeText and I'm not seeing too many others that are in position to replace SublimeGit.  Now that it is open source and there's no response from the owner, maybe it's time to organize a fork.  It would be a shame to start from scratch when this package is perfectly serviceable.

Hopefully the owner will pop-up and resolve this in a manner workable for him and the rest of us.

**Comment by Bogh** [comment]
True, I really like the implementation here over other Git plugins. I'd be happy to contribute to this.

**Comment by buildersbrewery** [comment]
@miped Is there anything you need help with?

**Comment by miped** [comment]
First, i'd like to say that the reports of my death has been greatly exaggerated. I'm still around and alive and kicking.

I honestly forgot about the pull request. My bad. I'll take a look at it this weekend.

As for forking, i don't think that's necessary, and it's gonna be a bit of a chore getting it set up in the package control channels. I'm more than happy to add collaborators to this project.

**Comment by sbuttgereit** [comment]
Glad to see you back @miped.  I would love to help you out, but could only do so in a very limited fashion; I'm not a Python developer, which I imagine would be prerequisite, so I'd only be helpful in some auxiliary role.  I do think if there are willing people with the right skills to help you maintain things, you'd have a stronger project overall.  Anyway, just wanted to say glad to see the recent activity.  Cheers.

**Comment by Vincent--** [comment]
Hey @miped 

Thank you for such a good project: I use it everyday and it's the most efficient way to control git from sublimetext in my opinion 😄 ! But the stack of PR and issues is slowly growing and without any activity on this repo, people will slowly but surely start to look at other alternatives 😞 

How could we prevent that? Are you happy to move the project to https://github.com/SublimeText? If you prefer to keep everything here, @buildersbrewery and maybe some others seem to be able to help you.

Thanking you in advance for your actions on that.

Regards,
Vincent.

**Comment by sbuttgereit** [comment]
I get the feeling we are back to where we were in July/16.  

This is still one of the better Git extensions (I'm using others right now, and would like to return to this one) and I'd hate to see it just dying.  

I fully support seeing this project being moved to https://github.com/SublimeText and I've been watching since @Vincent-- 's post to see if there would be a response.  I think @miped did some really good work getting this project to this state, but has clearly demonstrated either he hasn't the time and/or interest in continuing to support the project.  I get it, I have projects like that, too, which I've just shelved... I even have some wishful thinking to get back to them someday, too... though it's unlikely.

If @miped isn't amenable to moving the project soon, I've cloned the repo and would be happy to get a fork going under https://github.com/SublimeText if possible.  This situation reminds me of the gitflow situation (https://github.com/nvie/gitflow) where the original gitflow was forked and reborn as gitflow-avh (https://github.com/petervanderdoes/gitflow-avh) and the fork is now the more commonly used version that is regularly maintained.

**Comment by buildersbrewery** [comment]
I opened this issue, to ask first before moving on. It's an easy chore to simply redirect users of this package via Package Control.

If you - @sbuttgereit - would be willing to take over, I'm all for it. Whatever works, right.

I suggested the @sublimetext github organization in the first place because that would distribute chores amongst a group of people who know what they are doing.

**Comment by sbuttgereit** [comment]
@buildersbrewery I'll take a look on the weekend or while I'm on a business trip I'm taking next week.  I like the idea of getting it to the @sublimetext github organization for precisely the reasons you state.  I'll post a note here once there's a more concrete direction next week;  I did look at how packagecontrol.io works and it's pretty straightforward.

**Comment by miped** [comment]
I'm ok with moving the project, as long as i can retain commit rights to it. So just let me know what i need to do to make that happen.

**Comment by sbuttgereit** [comment]
@miped cool and sounds completely reasonable me.

I couldn't find much on who/how the @sublimetext GitHub org is managed, but they have an email address.  I'm dropping them a note to see what they say; I'll ask about the particulars.

**Comment by miped** [comment]
Cool, thanks for taking the lead on this :-)

**Comment by sbuttgereit** [comment]
Hi all--- 

I sent an email to the address listed for the @sublimetext organization a week ago and received approximately... no exactly... zero response.  It's unclear whose github ID(s) is associated with the people managing it so unless someone else here can point me to specific individuals... I'm thinking that a plan "B" might be in order.

@miped assuming nothing changes on the @sublimetext front; would you be willing to add me as someone that can take on some management functions on this repository?  That's an imperfect solution for the specific technical judgements that need to be made (I don't specialize in any of the technologies that your package/sublime text uses), but helping facilitate a community process is something I would be very comfortable with.  Without building too much ceremony for something like this... if we have a basic set of ground rules, perhaps we can get a "call list" of some community PR reviewers with appropriate technical skill that, while not being responsible for being full maintainers, but can drop in and say yes/no a given PR is reasonable, we can get contributions in without it being a complete mess.  Naturally, if others with appropriate technical skills want to be maintainers proper... I wouldn't object... but otherwise I would mostly being sure that things get merged, that merged stuff gets updated for package control, etc.

**Comment by Vincent--** [comment]
That sounds like a plan 😄 Thanks for your time on that, @sbuttgereit 👍

**Comment by miped** [comment]
@sbuttgereit I've added you as a collaborator

**Comment by sbuttgereit** [comment]
HI all--

At this point, unless there objection, I'm going to close this issue.  The plan as of now is to stay here and so I suggest giving the new arrangement a try and see how it goes.

Just a little expectation setting.  I'm more than happy to contribute time here, but just like many people taking on a role like this: it's not my day job, or even my side project, so I'll have some constraints.  I will devote some time each week, usually on the weekends for this, with some exceptions as conditions warrant (I won't log in on vacation for example 😄  ).  So, insofar as I can help, I have to be honest and say things will move slowly, but move regularly on a weekly cadence.  If that ever changes I'll also commit to let everyone know that I can't continue.

I expect to post more during the week and also respond to some of items that are outstanding.  @miped I'll reach out to you separately with some suggestions; not sure how much time you have, but definitely want to be sure I'm working with you.

Cheers!
SCB

**Comment by Vincent--** [comment]
👍
