### ISSUE TITLE
git checkout - switch to existing remote branch for the first time

### ISSUE THREAD

**Issue by saschamt** [SublimeGit/SublimeGit#29]
Hey Michael.
Great work on SublimeGit so far. It has become invaluable to me. Thanks for the tool!

One thing I've noticed is that when checking out existing branches (on Github in my case) that haven't been checked out locally before, the intelligent git checkout feature that is described in "git help checkout", which detects the existing remote branch and basically runs 

```
git checkout -b <branch> --track <origin>/<branch>
```

is not used and/or doesn't work. When I do checkout via SublimeGit and put in the name of the new branch nothing happens. This is on the newest version of ST2. ST3 has the same problem, although everything else runs really good in SublimeGit land. I'm fairly new to Git and might be missing something here. Any thoughts?

**Comment by stevage** [comment]
Just checking, still no update on this? Easiest solution might be to just list all the non-local branches after the local ones:

```
  somebranch
  master
* currentbranch
  origin/somenewbranch
  myrepo/anothernonlocalbranch
```

**Comment by tomi-roam** [comment]
+1 I'm running into this as well. I have to manually check out branches created by others the first time. This is somewhat annoying when using feature branches and performing reviews.

**Comment by frizop** [comment]
+1 running into this as well.

**Comment by lorenz** [comment]
+1

**Comment by IschaGast** [comment]
+1

**Comment by tomi-timetac** [comment]
+1

**Comment by fabriciomassula** [comment]
+1

**Comment by TJKresch** [comment]
+1

Not being able to do do this in `SublimeGit` forces me to have have a terminal tab open all the time just in case. It's a common-enough use-case that git added a shortcut for it. Instead of having to: 

1. Create and checkout a new branch locally,
2. Set it to track the remote branch, and then
3. Fetch the remote branch,

git lets you just type `git checkout remote-branch-name` where `remote-branch-name` is just the name of the remote branch you want, not including the remote name (e.g. `my-branch`, not `origin/my-branch`) and then all 3 of those steps happen automatically. 

I haven't looked under the hood of SublimeGit yet to see how it actually works, but if it somehow generates command-line git commands, then this should be pretty easy using the shorthand syntax I mentioned above. I guess the main piece that's missing is getting the names of the remote branches in the first place. (As there's no strict equivalent for `git branch {--remote | -r}` at the moment). 

Overall, I think the best UX for a solution to this will probably be to add a new command called `git: checkout remote branch` which: 

1. Displays a list of all remote branches (as with `git branch -r` from the command line), possibly filtering out those that you're already tracking with one of your local branches;
2. Allows the user to pick one;
3. Strips the `remote-name/` from the beginning of the full name `remote-name/branch-name`; and then
4. Plugs the resulting `branch-name` into the git CLI method `git checkout branch-name`. 

This would be way more convenient than doing it from the command line, since there's no way to combine `git branch -r` with `git checkout remote-branch-name`. I usually end up copy/pasting the branch name I want, which is annoying. 

The solution that @stevage suggested would work too, but that would add a potentially-significant amount of bloat to the options returned by `git: checkout`. It would also be combining two operations that are pretty different: "checking out a local branch" vs "creating a new local branch from a remote branch". I think it would probably be cleaner to keep them separate.

**Comment by stevage** [comment]
>Overall, I think the best UX for a solution to this will probably be to add a new command called git: checkout remote branch which:

This already exists. Maybe you still have an older version? (Or maybe it hasn't been released yet - I'm running the dev branch.) The action is called "git: checkout remote branch as local" and works much as you describe. Somewhere else I've suggested a slight refinement to the UX by merging it into the other "git: checkout" command, and just listing remote, non-local branches below others.

**Comment by TJKresch** [comment]
Thanks @stevage. Are you a contributor? 

It must be the development version. I made sure I forked the latest version of master (there were no other branches) before I started hacking on a solution and I compared with the current `PackageControl` version just to make sure. 

Any idea when a version with this functionality included will be released?

**Comment by miped** [comment]
@stevage @TJKresch It does not currently exists, i think @stevage might be using another plugin (maybe the Git one?)

@TJKresch Thanks for the pull request. I'll try and take a look at it this week.

**Comment by TJKresch** [comment]
@miped Great, thanks. Just let me know if there's anything else I can do to help with this.

**Comment by stevage** [comment]
Oh, I'm so sorry. Yeah, I switched to GitSavvy - didn't realise this thread was from SublimeGit. Oops.

**Comment by naml3i** [comment]
> +1
> 
> Not being able to do do this in `SublimeGit` forces me to have have a terminal tab open all the time just in case. It's a common-enough use-case that git added a shortcut for it. Instead of having to:
> 
> 1. Create and checkout a new branch locally,
> 2. Set it to track the remote branch, and then
> 3. Fetch the remote branch,
> 
> git lets you just type `git checkout remote-branch-name` where `remote-branch-name` is just the name of the remote branch you want, not including the remote name (e.g. `my-branch`, not `origin/my-branch`) and then all 3 of those steps happen automatically.
> 
> I haven't looked under the hood of SublimeGit yet to see how it actually works, but if it somehow generates command-line git commands, then this should be pretty easy using the shorthand syntax I mentioned above. I guess the main piece that's missing is getting the names of the remote branches in the first place. (As there's no strict equivalent for `git branch {--remote | -r}` at the moment).
> 
> Overall, I think the best UX for a solution to this will probably be to add a new command called `git: checkout remote branch` which:
> 
> 1. Displays a list of all remote branches (as with `git branch -r` from the command line), possibly filtering out those that you're already tracking with one of your local branches;
> 2. Allows the user to pick one;
> 3. Strips the `remote-name/` from the beginning of the full name `remote-name/branch-name`; and then
> 4. Plugs the resulting `branch-name` into the git CLI method `git checkout branch-name`.
> 
> This would be way more convenient than doing it from the command line, since there's no way to combine `git branch -r` with `git checkout remote-branch-name`. I usually end up copy/pasting the branch name I want, which is annoying.
> 
> The solution that @stevage suggested would work too, but that would add a potentially-significant amount of bloat to the options returned by `git: checkout`. It would also be combining two operations that are pretty different: "checking out a local branch" vs "creating a new local branch from a remote branch". I think it would probably be cleaner to keep them separate.

A bit late to the party but I totally agree. 
I have to figure it out myself after several trail-error and guesses... It's not the problem of "this function is already implemented or not", it's rather related to confusing UX/UI design. (Before using Sublime merge, I used SourceTree and command line, "Checkout Remote branch" sounds really natural: checkout a remote my_branch = create a local my_branch + copy the remote my_branch + start tracking it locally, yet SM only does 1 out of 3, it gets you the copy of the remote branch and if you continue to work on it without notifying that no local branch was created, you'd end up with a detached HEAD.

In Sublime merge, to do so one has to choose "Repository > Create Branch from Remote Branch...", but it's totally understandable that many would have confused the "Checkout Remote Branch..." for the function of "Create Branch from Remote Branch..."
